# Generated by Django 6.0.6 on 2026-06-18 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CONFIG_UPDATE', 'Configuration Updated'), ('CONFIG_TEST', 'Configuration Tested'), ('API_CALL', 'API Call'), ('API_ERROR', 'API Error'), ('KEY_CHANGE', 'API Key Changed'), ('ENABLE', 'API Enabled'), ('DISABLE', 'API Disabled')], max_length=20)),
                ('details', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='APIConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=255)),
                ('is_enabled', models.BooleanField(default=True)),
                ('last_test', models.DateTimeField(blank=True, null=True)),
                ('test_status', models.BooleanField(default=False)),
                ('test_message', models.TextField(blank=True)),
                ('rate_limit_remaining', models.IntegerField(default=1000)),
                ('rate_limit_reset', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Configuration',
                'verbose_name_plural': 'API Configurations',
            },
        ),
        migrations.CreateModel(
            name='IntelligenceSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_type', models.CharField(choices=[('IP', 'IP Address'), ('EMAIL', 'Email Address'), ('PHONE', 'Phone Number'), ('URL', 'URL/Domain'), ('BREACH', 'Breach Intelligence')], max_length=10)),
                ('query', models.CharField(max_length=500)),
                ('results', models.JSONField(default=dict)),
                ('risk_score', models.IntegerField(blank=True, null=True)),
                ('risk_level', models.CharField(blank=True, max_length=20, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_high_risk', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intelligence_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='IntelligenceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_format', models.CharField(choices=[('PDF', 'PDF'), ('CSV', 'CSV'), ('JSON', 'JSON')], max_length=4)),
                ('file_path', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('download_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intelligence_reports', to=settings.AUTH_USER_MODEL)),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='intelligence.intelligencesearch')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='intelligencesearch',
            index=models.Index(fields=['user', 'timestamp'], name='intelligenc_user_id_d512af_idx'),
        ),
        migrations.AddIndex(
            model_name='intelligencesearch',
            index=models.Index(fields=['search_type', 'timestamp'], name='intelligenc_search__a1d050_idx'),
        ),
        migrations.AddIndex(
            model_name='intelligencesearch',
            index=models.Index(fields=['risk_score'], name='intelligenc_risk_sc_aa9f4d_idx'),
        ),
    ]
