# Generated by Django 6.0.6 on 2026-06-18 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiauditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intelligence_audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='apiconfiguration',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intelligence_api_config_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='apiauditlog',
            index=models.Index(fields=['user', 'timestamp'], name='intelligenc_user_id_58cf52_idx'),
        ),
        migrations.AddIndex(
            model_name='apiauditlog',
            index=models.Index(fields=['action'], name='intelligenc_action_d30aaf_idx'),
        ),
    ]
