# Generated by Django 6.0.6 on 2026-06-19 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('service_type', models.CharField(choices=[('IPQS', 'IPQualityScore'), ('VT', 'VirusTotal'), ('SHODAN', 'Shodan'), ('ABUSEIPDB', 'AbuseIPDB'), ('GREYNOISE', 'GreyNoise'), ('CUSTOM', 'Custom API')], max_length=20)),
                ('api_key', models.CharField(max_length=500)),
                ('base_url', models.URLField(blank=True, help_text='Optional: Override default API endpoint')),
                ('is_enabled', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('last_verified', models.DateTimeField(blank=True, null=True)),
                ('rate_limit', models.IntegerField(default=1000, help_text='Maximum requests per period')),
                ('rate_limit_period', models.CharField(choices=[('minute', 'Per Minute'), ('hour', 'Per Hour'), ('day', 'Per Day'), ('month', 'Per Month')], default='day', max_length=20)),
                ('timeout', models.IntegerField(default=30, help_text='Request timeout in seconds')),
                ('max_retries', models.IntegerField(default=3, help_text='Maximum retry attempts on failure')),
                ('extra_config', models.JSONField(blank=True, default=dict, help_text='Additional configuration in JSON format')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Service',
                'verbose_name_plural': 'API Services',
                'ordering': ['service_type'],
                'unique_together': {('user', 'service_type')},
            },
        ),
        migrations.CreateModel(
            name='APIAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CONFIG_UPDATE', 'Configuration Updated'), ('CONFIG_TEST', 'Configuration Tested'), ('API_CALL', 'API Call'), ('API_ERROR', 'API Error'), ('KEY_CHANGE', 'API Key Changed'), ('ENABLE', 'API Enabled'), ('DISABLE', 'API Disabled'), ('SERVICE_CREATE', 'Service Created'), ('SERVICE_UPDATE', 'Service Updated'), ('SERVICE_DELETE', 'Service Deleted')], max_length=20)),
                ('details', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Audit Log',
                'verbose_name_plural': 'API Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='core_settin_user_id_03d040_idx'), models.Index(fields=['action'], name='core_settin_action_116a43_idx')],
            },
        ),
        migrations.CreateModel(
            name='APIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=10)),
                ('request_data', models.JSONField(blank=True, default=dict)),
                ('response_status', models.IntegerField()),
                ('response_data', models.JSONField(blank=True, default=dict)),
                ('response_time', models.FloatField(help_text='Response time in seconds')),
                ('is_error', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='core_settings.apiservice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_usage_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Usage Log',
                'verbose_name_plural': 'API Usage Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='core_settin_user_id_85fabc_idx'), models.Index(fields=['service', 'timestamp'], name='core_settin_service_7b3990_idx')],
            },
        ),
    ]
