import json
import csv
import io
import os
from datetime import datetime
from django.conf import settings
from django.core.files.base import ContentFile

class ReportGenerator:
    """Service for generating investigation reports"""
    
    @staticmethod
    def generate_pdf(search_result, user):
        """Generate PDF report (placeholder)"""
        # For now, return a simple text report
        report_content = f"""
        CYBER THREAT INTELLIGENCE REPORT
        ================================
        
        Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
        Analyst: {user.get_full_name() or user.username}
        Search Type: {search_result.get('search_type', 'Unknown')}
        Query: {search_result.get('query', 'N/A')}
        Risk Level: {search_result.get('risk_level', 'Unknown')}
        
        RESULTS:
        {json.dumps(search_result.get('results', {}), indent=2)}
        
        This report is for authorized use only.
        Generated by Cyber Crime Investigation Platform
        """
        return report_content.encode('utf-8')
    
    @staticmethod
    def generate_csv(search_result):
        """Generate CSV report"""
        output = io.StringIO()
        writer = csv.writer(output)
        
        # Write header
        writer.writerow(['Field', 'Value'])
        writer.writerow(['=' * 40, '=' * 40])
        
        # Write metadata
        writer.writerow(['Report Generated', datetime.now().isoformat()])
        writer.writerow(['Search Type', search_result.get('search_type', 'Unknown')])
        writer.writerow(['Query', search_result.get('query', 'N/A')])
        writer.writerow(['Risk Level', search_result.get('risk_level', 'Unknown')])
        writer.writerow([])
        
        # Write results
        results = search_result.get('results', {})
        ReportGenerator._flatten_dict(writer, results, '')
        
        return output.getvalue()
    
    @staticmethod
    def _flatten_dict(writer, data, prefix=''):
        """Flatten nested dict for CSV export"""
        if isinstance(data, dict):
            for key, value in data.items():
                new_prefix = f"{prefix}.{key}" if prefix else key
                ReportGenerator._flatten_dict(writer, value, new_prefix)
        elif isinstance(data, list):
            for i, item in enumerate(data):
                ReportGenerator._flatten_dict(writer, item, f"{prefix}[{i}]")
        else:
            writer.writerow([prefix, data])
    
    @staticmethod
    def generate_json(search_result):
        """Generate JSON report"""
        return json.dumps(search_result, indent=2, default=str)
    
    @staticmethod
    def save_report(search_result, user, report_format):
        """Save report to database and file system"""
        from intelligence.models import IntelligenceReport
        
        # Generate report content
        if report_format == 'PDF':
            content = ReportGenerator.generate_pdf(search_result, user)
            extension = 'pdf'
        elif report_format == 'CSV':
            content = ReportGenerator.generate_csv(search_result)
            extension = 'csv'
        elif report_format == 'JSON':
            content = ReportGenerator.generate_json(search_result)
            extension = 'json'
        else:
            raise ValueError(f"Unsupported format: {report_format}")
        
        # Create filename
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        filename = f"intelligence_report_{timestamp}.{extension}"
        
        # Create directory if it doesn't exist
        reports_dir = os.path.join(settings.MEDIA_ROOT, 'reports')
        os.makedirs(reports_dir, exist_ok=True)
        
        # Save file
        file_path = os.path.join(reports_dir, filename)
        with open(file_path, 'wb') as f:
            if isinstance(content, str):
                f.write(content.encode('utf-8'))
            else:
                f.write(content)
        
        # Create database record
        report = IntelligenceReport.objects.create(
            search_id=search_result.get('id'),
            user=user,
            report_format=report_format,
            file_path=os.path.join('reports', filename),
            title=f"Intelligence Report - {search_result.get('query', 'Unknown')}",
            description=f"Report for {search_result.get('search_type', 'Unknown')} investigation"
        )
        
        return report