# Generated by Django 6.0.6 on 2026-06-20 14:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('raw_email', models.TextField()),
                ('parsed_email', models.JSONField(default=dict)),
                ('headers', models.JSONField(default=dict)),
                ('spf_result', models.JSONField(default=dict)),
                ('dkim_result', models.JSONField(default=dict)),
                ('dmarc_result', models.JSONField(default=dict)),
                ('route_timeline', models.JSONField(default=list)),
                ('domain_intelligence', models.JSONField(default=dict)),
                ('ip_intelligence', models.JSONField(default=list)),
                ('url_findings', models.JSONField(default=list)),
                ('attachment_findings', models.JSONField(default=list)),
                ('iocs', models.JSONField(default=dict)),
                ('osint_data', models.JSONField(default=dict)),
                ('social_profiles', models.JSONField(default=list)),
                ('github_findings', models.JSONField(default=list)),
                ('breach_data', models.JSONField(default=list)),
                ('gravatar_data', models.JSONField(default=dict)),
                ('threat_score', models.IntegerField(default=0)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis_duration', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('UPLOAD', 'Email Uploaded'), ('ANALYZE', 'Analysis Started'), ('COMPLETE', 'Analysis Completed'), ('FAILED', 'Analysis Failed'), ('REPORT', 'Report Generated'), ('DOWNLOAD', 'Report Downloaded')], max_length=10)),
                ('details', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_history', to=settings.AUTH_USER_MODEL)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='email_forensics.emailanalysis')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EmailReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.IntegerField(default=0)),
                ('format', models.CharField(default='PDF', max_length=10)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('download_count', models.IntegerField(default=0)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='email_forensics.emailanalysis')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='IOC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ioc_type', models.CharField(choices=[('EMAIL', 'Email Address'), ('DOMAIN', 'Domain'), ('URL', 'URL'), ('IPV4', 'IPv4 Address'), ('IPV6', 'IPv6 Address'), ('MD5', 'MD5 Hash'), ('SHA1', 'SHA1 Hash'), ('SHA256', 'SHA256 Hash')], max_length=10)),
                ('value', models.CharField(max_length=500)),
                ('context', models.TextField(blank=True)),
                ('is_malicious', models.BooleanField(default=False)),
                ('threat_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ioc_objects', to='email_forensics.emailanalysis')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='emailanalysis',
            index=models.Index(fields=['user', 'created_at'], name='email_foren_user_id_2c2f84_idx'),
        ),
        migrations.AddIndex(
            model_name='emailanalysis',
            index=models.Index(fields=['risk_level'], name='email_foren_risk_le_ebe8eb_idx'),
        ),
        migrations.AddIndex(
            model_name='emailanalysis',
            index=models.Index(fields=['status'], name='email_foren_status_a313d5_idx'),
        ),
        migrations.AddIndex(
            model_name='ioc',
            index=models.Index(fields=['ioc_type', 'value'], name='email_foren_ioc_typ_c03c3c_idx'),
        ),
        migrations.AddIndex(
            model_name='ioc',
            index=models.Index(fields=['is_malicious'], name='email_foren_is_mali_eb26c5_idx'),
        ),
    ]
